### ISSUE TITLE
Github Enterprise support

### ISSUE THREAD

**Issue by dadosch** [matrix-org/matrix-hookshot#112]
Currently, as far as I can see only github.com is supported. However, Github Enterprise also has API & Github Apps (https://docs.github.com/en/enterprise-server@3.3/rest/guides/getting-started-with-the-rest-api), so at least on a quick glance, support for Github Enterprise might be possible technically.

**Comment by Half-Shot** [comment]
Yeah, if it's a matter of repointing URLs then support is easy, but I don't currently have access to an enterprise instance so testing is hard. If someone wants to PR the change and test it, happy to review / merge :+1:
