### ISSUE TITLE
provide a (sample) grafana dashboard

### ISSUE THREAD

**Issue by HarHarLinks** [matrix-org/matrix-hookshot#147]
which could then also be added to matrix-docker-ansible-deploy thusly: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/5a8b17c1df268e7fc206ed72bc8c7a7d56626c1b/group_vars/matrix_servers#L2125

**Comment by Half-Shot** [comment]
Good thing to have, but afraid I've not had the time yet. I think we're likely to have something once I've started working on deploying this at work, and I can commit that back.
