### ISSUE TITLE
don't post tokens to the room they're to be used in

### ISSUE THREAD

**Issue by HarHarLinks** [matrix-org/matrix-hookshot#161]
e.g. `!hookshot webhook some-name` will post an otherwise unprotected url to the room you're setting up for webhooks.

because of this you have to take special care to redact things when you want to create a public room that receives a webhook.

appservice-webhooks handled this by replying in you private admin room instead.

**Comment by Half-Shot** [comment]
We should potentially just send it to the user's admin room (creating one if necessary)
