### ISSUE TITLE
add ability to format generic webhooks as notice, emote

### ISSUE THREAD

**Issue by HarHarLinks** [matrix-org/matrix-hookshot#179]
The old appservice could send emote and more importantly notice msgtypes: https://github.com/turt2live/matrix-appservice-webhooks#json-body-for-posting-messages

Hookshot should offer the same functionality to support this. It should be settable by a `msgtype` field in the webhook data or similar, and ideally also via the jstransform option. This would enable some pretty [neat](https://github.com/HarHarLinks/matrix-webhook-receiver#noisy-notifications) use cases.

**Comment by Half-Shot** [comment]
This is fixed via transform functions in https://github.com/matrix-org/matrix-hookshot/pull/282.
