### ISSUE TITLE
mask the startup error `User ID already taken`

### ISSUE THREAD

**Issue by HarHarLinks** [matrix-org/matrix-hookshot#193]
the bridge will lament every time on startup that account can't be created since it already exists, according to yourself that's a false alarm.

https://matrix.to/#/!TlZdPIYrhwNvXlBiEk:half-shot.uk/$aERlFBlVtkEVj5r3lok17K0Ymw9BhkptGWCHkSxMUCk?via=half-shot.uk&via=matrix.org&via=envs.net

**Comment by Half-Shot** [comment]
Fixed in #229
