### ISSUE TITLE
Generic Webhook link from bot does not include port and protocol

### ISSUE THREAD

**Issue by sensor-freak** [matrix-org/matrix-hookshot#206]
After joining a Matrix room one may generate a webhook link by using `!hookshot webhook example`. The bot then responds with the requested hook. However, this hook does not contain the correct protocol, and also not a non-standard port from the Matrix homeserver:

```
Room configured to bridge webhooks. Please configure your webhook source to use 
matrix.abcde.net/hookshot/webhooks/xxxxxxxx-yyyy-zzzz-aaaa-bbbbbbbbbbbb
```

The correct link (in my case) should be http**s**://matrix.abcde.net**:444**/hookshot/webhooks/xxxxxxxx-yyyy-zzzz-aaaa-bbbbbbbbbbbb (and yes, with that fixed link the hook works as expected.)

Presumably these parts may be configured somewhere, but I could't find the correct place where this might be.

**Comment by HarHarLinks** [comment]
What is your `urlPrefix` setting?
https://half-shot.github.io/matrix-hookshot/setup/webhooks.html#configuration

**Comment by sensor-freak** [comment]
Currently: `urlPrefix: matrix.abcde.net/hookshot/webhooks`

If this is the relevant setting, then I assume I have to fix it in [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy)?

**Comment by HarHarLinks** [comment]
I'm the author of the hookshot role in matrix-docker-ansible-deploy, I'm working on a fix.
What is your configuration, how did you configure port 444? `matrix_nginx_proxy_container_https_host_bind_port`?

**Comment by HarHarLinks** [comment]
Thank you for bringing this up, @sensor-freak. You can apply the patch https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/1635 if you want to test it before it gets merged, it should set both url scheme and port (hoping I haven't overlooked anything).

**Comment by sensor-freak** [comment]
Actually the port is only specified in the `well-known/matrix/client` file. That file is served by a Plesk based domain server. Matrix is managed with Ansible and served through a traefik reverse proxy which handles TLS termination. That proxy is configured to provide access through port 444. Additionally I have specified some location settings for nginx which forward some paths from the main domain to port 444. - Maybe I should add a location for webhooks, too. (Will try tomorrow.)

Within the playbook configuration there is no hint to port 444, so matrix itself does not know that it is served behind that port. So the fix above will not work in my case.

But thank you in any way! I've found out that first I have to fix my deployment. If there are still issues then, I will come back.

**Comment by HarHarLinks** [comment]
That is quite a particular setup :D 
In that case, `matrix_hookshot_generic_urlprefix: "https://{{ matrix_server_fqn_matrix }}:444{{ matrix_hookshot_generic_endpoint }}" seems like the reasonable thing to do.

If you run into more issues with the playbook role, feel free to ping me in an issue over at https://github.com/spantaleev/matrix-docker-ansible-deploy.

**Comment by Half-Shot** [comment]
The `urlPrefix` setting *should* be your public URL, so from a hookshot standpoint if the config doesn't include exactly that, it won't work.
