### ISSUE TITLE
Generic Webhook does not place GET parameters in the message body

### ISSUE THREAD

**Issue by sensor-freak** [matrix-org/matrix-hookshot#208]
It seems that the generic webhook does not correctly convert the request parameters from a GET request into the body of the message. At least I could only see an empty message (`{}`) in the target room with all GET requests. (HTTP status code is 200, the response body contains `OK`.

The problem might be located in `Webhooks.ts:onGenericPayload()`. I have no idea if the assignment in line 131 (`body = req.query;`) is sufficient for the intended purpose.

With PUT and POST (and the correct mime type given) the payload arrives at the room.

**Comment by HarHarLinks** [comment]
i can confirm this issue

**Comment by Half-Shot** [comment]
I was unable to reproduce this one. I tried `http://mydomain.com/005ea737-9019-46d2-bea3-9897da0f60b4?foo=bar&bar=baz&foo=baz` which gave me the expected object.

![image](https://user-images.githubusercontent.com/2072976/156634665-05480ada-c45d-48d3-970e-8280a27f9092.png)

**Comment by Procuria** [comment]
I can reproduce this behavior.  I have a **https** "environment" (URL: https://matrix.computerlie.be...) If I POST to a **http* webhook, my request becomes a GET. 
Test --> POST to http://matrix.computerlie.be/hookshot/webhooks/7a274072..... with 
````json
{
    "text" : "Hello",
    "html" : "Hello"
}
````
Result:
<img width="555" alt="2022-03-03_20h28_12" src="https://user-images.githubusercontent.com/37988494/156638480-3128502b-2d08-44bb-b7d8-3e42c1cddb63.png">

What additional information can I provide to support the troubleshooting?

**Comment by HarHarLinks** [comment]
![image](https://user-images.githubusercontent.com/2803622/156640751-b459f87d-00d3-45a9-86d3-e1099d2ee705.png)
![image](https://user-images.githubusercontent.com/2803622/156640773-cf840a06-37fd-4786-ac6a-56262a1c2b0b.png)

**Comment by Procuria** [comment]
@Half-Shot  Thanks to the hint of @HarHarLinks regarding the nginx config I found a working solution. 
If you  add `$is_args$args` to the location block of hookshot the query runs through. So the block has to look like this 
````
location ~ ^/hookshot/webhooks/(.*)$ {
          resolver 127.0.0.11 valid=5s;
    set $backend "matrix-hookshot:9000";
    proxy_pass http://$backend/$1$is_args$args;
    proxy_set_header Host $host;
}
````

**Comment by HarHarLinks** [comment]
docs for these variables seem legit. https://nginx.org/en/docs/http/ngx_http_core_module.html#var_args
so this is not a hookshot issue after all, but a playbook issue.
i have deployed Procuria's solution and it appears to work? I now GET
![image](https://user-images.githubusercontent.com/2803622/156654898-dd910b86-6be4-49d5-8244-efa232c50bc5.png)
with
```
Digest: sha256:32556eb5334575d244954ebf63dce714a1d3bce83cd4a9e36194b98ce3e3eee0
Status: Image is up to date for halfshot/matrix-hookshot:latest
docker.io/halfshot/matrix-hookshot:latest
```

**Comment by luismanson** [comment]
There is a PR open for a fix in the playbok: https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/1672

**Comment by Procuria** [comment]
PR is merged, I think we can close this issue.

**Comment by HarHarLinks** [comment]
@Half-Shot why is yours a code block and mine inline-code?

**Comment by Half-Shot** [comment]
Because I was testing a (now merged) feature at the same time :)

**Comment by HarHarLinks** [comment]
if you're referring to https://github.com/matrix-org/matrix-hookshot/pull/224, it is not merged yet :)

**Comment by sensor-freak** [comment]
I can confirm, the fix works. The parameters are now arriving in the room.
