### ISSUE TITLE
Github bridge left its own portal

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-hookshot#22]
I was already sitting in a `#github_owner_repo_num:example.org` portal when this happened:
![image](https://user-images.githubusercontent.com/1190097/62817774-30365180-baf9-11e9-8544-64c9285144c8.png)

**Comment by Half-Shot** [comment]
https://github.com/Half-Shot/matrix-github/blob/f6c7a2fe24a1f42489f065a68585fa5600bf8a61/src/GithubBridge.ts#L169-L183

**Comment by Half-Shot** [comment]
Since fixed.
