### ISSUE TITLE
Support GitLab `push` events

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-hookshot#252]
(`event_name = push`)

**Comment by HarHarLinks** [comment]
in my experience push events contain at most 20 commits, so in case you want to list them, there needs to be a fallback, compare [here](https://github.com/HarHarLinks/matrix-webhook-receiver/blob/48ce9ce59bf8f49294b2bf0937b9b30f21f2657a/examples/gitlab.jinja2#L8-L13).

https://docs.gitlab.com/ee/user/project/integrations/webhook_events.html#push-events
