### ISSUE TITLE
GitHub issue closing comment is sometimes picked up wrongly

### ISSUE THREAD

**Issue by jaywink** [matrix-org/matrix-hookshot#261]
**Describe the bug**

Unsure when this exactly happens, but it seems sometimes the GitHub closing comment is picked up wrongly. I'm assuming this happens if you have a checkbox on another comment, and then you check it + write a new comment closing the issue.

Would expect the last comment that closed the issue to the picked and posted, not the one that had the checkbox that was checked.

**Comment by Half-Shot** [comment]
>Unsure when this exactly happens, but it seems sometimes the GitHub closing comment is picked up wrongly. I'm assuming this happens if you have a checkbox on another comment, and then you check it + write a new comment closing the issue.

It could very well be this. GitHub's API doesn't include a "closing comment" in the close event so we guess based on the last sent comment in the chain (within the last 2 minutes). We do a dumb "last updated" timestamp check rather than filtering out edits, so we can fix that.
