### ISSUE TITLE
Distinct avatars per bridged service instance

### ISSUE THREAD

**Issue by HarHarLinks** [matrix-org/matrix-hookshot#275]
**Is your feature request related to a problem? Please describe.**
I think it's great to have the visualization of an avatar to distinguish things, e.g. using the default octocatbot to bridge a GitLab doesn't represent that properly.
Continuing that thought, this is even more interesting when e.g. your GitLab instance has a custom branded logo you can use.
This is especially important when multiple things are bridged in one room, but improves UX even with singular ones.

**Describe the solution you'd like**
- Ability to configure avatars either at the config.yml level similar to the default avatar it currently has
- and/or configure avatar at connection level, when creating a connection

**Additional context**
Related to #178

**Comment by Half-Shot** [comment]
I'd like to have it so that each service could have it's own distinct user (go-neb) style for this use case, it's just a bit of a refactor job at the moment.
