### ISSUE TITLE
widgets listener is missing from config.sample.yml

### ISSUE THREAD

**Issue by HarHarLinks** [matrix-org/matrix-hookshot#288]
https://github.com/matrix-org/matrix-hookshot/blob/7379346fc153472146b9afa606b818ee52b06499/docs/advanced/widgets.md?plain=1#L59 according to docs, but no further mention of this?

**Comment by HarHarLinks** [comment]
wait perhaps I was mistaken?
https://github.com/matrix-org/matrix-hookshot/blob/7379346fc153472146b9afa606b818ee52b06499/config.sample.yml#L147

**Comment by Half-Shot** [comment]
I think it's all there?

**Comment by HarHarLinks** [comment]
where is it by default, when the `widgets` section is enabled, but no listener is configured? if required, perhaps state explicitly that you need to add a listener to enable the widgets feature?

**Comment by Half-Shot** [comment]
Yeah, couldn't hurt to have a runtime check too.

**Comment by HarHarLinks** [comment]
and/or that config validator functionality you have
