### ISSUE TITLE
Git clone issue: Permission denied (publickey).

### ISSUE THREAD

**Issue by compgeniuses** [matrix-org/matrix-hookshot#347]
**Describe the bug**
Following the installation instructions detailed here:
git clone git@github.com:matrix-org/matrix-hookshot.git
cd matrix-hookshot
yarn # or npm i

a user gest the error
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**To Reproduce**
tyr making installation from any centos server
**Expected behavior**
the software would be cloned to the local folder

**Screenshots**
[root@org synapse]# git clone git@github.com:matrix-org/matrix-hookshot.git
Cloning into 'matrix-hookshot'...
Warning: Permanently added the ECDSA host key for IP address '140.82.121.4' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Half-Shot** [comment]
I've ended up suggesting people clone the HTTPS URL, I suspect *developers* will obviously want to use the SSH url which we can call out in our contributing file.
