### ISSUE TITLE
Hookshot Configuration widget dark theme

### ISSUE THREAD

**Issue by Twi1ightSparkle** [matrix-org/matrix-hookshot#348]
**Is your feature request related to a problem? Please describe.**
The Hookshot Configuration widget is too bright next to the other dark theme parts in Element.

**Describe the solution you'd like**
A dark theme for the Hookshot Configuration widget. Should switch between light and dark based on the selected Element theme.

**Describe alternatives you've considered**
I suppose one could hack this together with a browser custom-styling addon or by putting your own some custom CSS somewhere. But that's not really scalable or very user-friendly.

**Additional context**
🕶️

**Comment by HarHarLinks** [comment]
Quoting Half-Shot:

> It's just doing https://github.com/Half-Shot/matrix-spanner-widget/blob/c4dcbeb5a0c0eb78707bbfd48b3fa775620980e1/src/styling.css#L8-L13 in various places
