### ISSUE TITLE
[BUG] Webhook does not seem to be generated correctly

### ISSUE THREAD

**Issue by JustCodeIt4Head** [matrix-org/matrix-hookshot#357]
**Describe the bug**
When installing Matrix via Ansible in Docker via https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/prerequisites.md and adding a Webhook to a Room the Webhook does not seem to be generated correctly and results in a 404 Error when being used (replaced URl Data etc with Dummies for this Post)

`2022-05-17 12:38:05,122 - synapse.http.client - 726 - WARNING - GET-1855 - Got 404 when downloading https://matrix.domain.tld/hookshot/webhooks/647417c9-70e7-4283-a86a-42a5ba447ab5%3C/code%3E`

`May 17 12:38:06 matrixserver matrix-nginx-proxy[155068]: x.x.x.x - - [17/May/2022:12:38:06 +0000] "GET /_matrix/media/r0/preview_url?url=https%3A%2F%2Fmatrix.domain.tld%2Fhookshot%2Fwebhooks%2F647417c9-70e7-4283-a86a-42a5ba447ab5%253C%2Fcode%253E&ts=1652791080000 HTTP/1.0" 502 47 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0" "10.10.10.16"`

**To Reproduce**
1. Install Matrix + Components according to https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/prerequisites.md (worked previously till 10 Days ago)
2. Create a Room
3. Invite Hookshot User and create a Webhook according to documentation
4. Send Data (e.g. via Postman) to the Webhook

**Expected behavior**
Webhook should work as previously

**Additional context**
Reinstalled the whole Server 3 times + new Git Pull + routing the Server directly without Firewall to the WAN.
Using Debian 11 in a Proxmox VM with a Sophos XG as a Firewall.

Sadly, the Logs don't give any more Information (like the Daemon Log of Docker etc.) but it worked fine as of around 10 Days ago when using the same Ansible Playbook.

**Comment by Half-Shot** [comment]
Synapse is attempting to generate a thumbnail for your webhook and failing, but this isn't a bug. Sounds like there might be a bug in the playbook, but I think you need to provide logs for hookshot (NOT Synapse/nginx).

**Comment by JustCodeIt4Head** [comment]
Where is Hookshot saving the logs to? Seems not to be in the daemon log of docker.

**Comment by Half-Shot** [comment]
Hookshot *should* log to the usual docker output, unless matrix-docker-ansible-deploy is doing something strange. I'd try debugging with https://matrix.to/#/#matrix-docker-ansible-deploy:devture.com first to see if they have an idea?

**Comment by JustCodeIt4Head** [comment]
Hi,
so here are the Logs related to the Hookshot Webhook:
`May 17 15:03:12 debian matrix-nginx-proxy[55071]: 172.18.0.3 - - [17/May/2022:20:03:12 +0000] "OPTIONS /_matrix/media/r0/preview_url?url=https%3A%2F%2Fmatrix.domain.de%2Fhookshot%2Fwebhooks%2F31f0c080-5f81-43a8-bb86-7467900ac216%253C%2Fcode%253E&ts=1652817720000 HTTP/1.0" 204 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36" "x.x.x.x"

May 17 15:03:12 debian matrix-nginx-proxy[55071]: x.x.x.x - - [17/May/2022:20:03:12 +0000] "OPTIONS /_matrix/media/r0/preview_url?url=https%3A%2F%2Fmatrix.domain.de%2Fhookshot%2Fwebhooks%2F31f0c080-5f81-43a8-bb86-7467900ac216%253C%2Fcode%253E&ts=1652817720000 HTTP/2.0" 204 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36" "-"

May 17 15:03:12 debian matrix-nginx-proxy[55071]: 172.18.0.1 - - [17/May/2022:20:03:12 +0000] "GET /hookshot/webhooks/31f0c080-5f81-43a8-bb86-7467900ac216%3C/code%3E HTTP/1.1" 404 181 "-" "Synapse (bot; +https://github.com/matrix-org/synapse)" "-"
May 17 15:03:12 debian matrix-synapse[55070]: 2022-05-17 20:03:12,669 - synapse.http.client - 726 - WARNING - GET-463 - Got 404 when downloading https://matrix.domain.de/hookshot/webhooks/31f0c080-5f81-43a8-bb86-7467900ac216%3C/code%3E

May 17 15:03:12 debian matrix-nginx-proxy[55071]: 172.18.0.3 - - [17/May/2022:20:03:12 +0000] "GET /_matrix/media/r0/preview_url?url=https%3A%2F%2Fmatrix.domain.de%2Fhookshot%2Fwebhooks%2F31f0c080-5f81-43a8-bb86-7467900ac216%253C%2Fcode%253E&ts=1652817720000 HTTP/1.0" 502 47 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36" "x.x.x.x"

May 17 15:03:12 debian matrix-nginx-proxy[55071]: x.x.x.x - - [17/May/2022:20:03:12 +0000] "GET /_matrix/media/r0/preview_url?url=https%3A%2F%2Fmatrix.domain.de%2Fhookshot%2Fwebhooks%2F31f0c080-5f81-43a8-bb86-7467900ac216%253C%2Fcode%253E&ts=1652817720000 HTTP/2.0" 502 47 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36" "-"

May 17 15:03:35 debian matrix-nginx-proxy[55071]: x.x.x.x - - [17/May/2022:20:03:35 +0000] "GET /hookshot/webhooks/31f0c080-5f81-43a8-bb86-7467900ac216 HTTP/2.0" 404 159 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36" "-"

May 17 15:04:17 debian matrix-nginx-proxy[55071]: x.x.x.x - - [17/May/2022:20:04:17 +0000] "GET /hookshot/webhooks/31f0c080-5f81-43a8-bb86-7467900ac216 HTTP/2.0" 404 159 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36" "-"`


I think the Issue is with this Line:
synapse.http.client - 726 - WARNING - GET-463 - Got 404 when downloading https://matrix.domain.de/hookshot/webhooks/31f0c080-5f81-43a8-bb86-7467900ac216%3C/code%3E

Hes appending some HTML Code (code%3E) at the End of the Webhook so it might not be Generated correctly?
I opened a Bug Report with the Playbook Developer here: https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/1832

I did a complete Reinstall from Scratch on another System with no Firewall in Front of the Server and got the same Issue that the Webhook just says Cannot GET /31f0c080-5f81-43a8-bb86-7467900ac216.
As said we used it like 10-12 Days ago without Issue but had to rebuild the Server due to a Malfunction of the VM.
We also tried older specific Versions of Hookshot to see if a change broke it but no luck with that too

**Comment by Half-Shot** [comment]
I'm afraid none of those logs are helpful, and you can discount any errors from Synapse being the culprit.

**Comment by JustCodeIt4Head** [comment]
Hello,
and I thought I might have found it.
I noticed another Error in the Daemon Log:
matrixserver matrix-synapse[34822]: 2022-05-17 14:04:52,684 - synapse.appservice.scheduler - 404 - ERROR - as-sender-matrix-hookshot-1 - Error creating appservice transaction

Could that be the Issue?

I will export and redact the complete daemon.log in regard to hookshot from my Test System later today and Post it here. We are also trying to get a Commit State from early Apil working (the last time we know the Playbook worked 100%).

Btw i also get a Error when i try to set the permissions via the vars.yml with:
```
matrix_hookshot_permissions:
   - actor: "@admin:domain.tld"
     services:
       - service: "*"
         level: admin
```
The Playbook then complains about the : at admin:domain.tld as being unexpected (tried " and ').
It's not a faulty yml as far I can tell (in regard to positioning).
Can I check the permissions of hookshot after I have installed it?

**Comment by JustCodeIt4Head** [comment]
> > matrixserver matrix-synapse[34822]: 2022-05-17 14:04:52,684 - synapse.appservice.scheduler - 404 - ERROR - as-sender-matrix-hookshot-1 - Error creating appservice transaction
> 
> Now that _does_ look like a smoking gun. I'm not quite sure how the ansible playbook works but it's worth asking them for help on this one.

Okay, i will add it :)

**Comment by psolyca** [comment]
I'm using a Docker version of hookshot (halfshot/matrix-hookshot) and got the same malformed error as mentionned when typing ```!hookshot webhook test```. The link send is like ```https://matrix.mydomain.ovh/hookshot/webhook/96ea5f13-e7f7-4273-a407-81d6916b79c3%3C/code%3E```
My synapse/matrix is on a container also and communication work.
The only trouble is this malformed URL (also the widget but it's another story).

**Comment by JustCodeIt4Head** [comment]
> I'm using a Docker version of hookshot (halfshot/matrix-hookshot) and got the same malformed error as mentionned when typing `!hookshot webhook test`. The link send is like `https://matrix.mydomain.ovh/hookshot/webhook/96ea5f13-e7f7-4273-a407-81d6916b79c3%3C/code%3E` My synapse/matrix is on a container also and communication work. The only trouble is this malformed URL (also the widget but it's another story).

We tried to recreate it with the Versions we had earlier in April when it worked and got the same Issue, which is strange.
Do you use the latest Docker Images?

Im working on another Try at the weekend at let u know

**Comment by psolyca** [comment]
Yes latest Docker image.
So is it `hookshot` or `synapse` ? I did not find the code which make the URL in `hookshot` .
Also, if I try to send a request to the cleaned URL, I have this in my docker logs `[Bridge] generic-webhook.event for [empty]`  and the response is `404` with message `{"ok":false,"error":"Webhook not found"}`.

**Comment by JustCodeIt4Head** [comment]
> Yes latest Docker image. So is it `hookshot` or `synapse` ? I did not find the code which make the URL in `hookshot` . Also, if I try to send a request to the cleaned URL, I have this in my docker logs `[Bridge] generic-webhook.event for [empty]` and the response is `404` with message `{"ok":false,"error":"Webhook not found"}`.
> 
> EDIT : I have also en ` Event not found` message time to time.

I suspect Synapse, Docker or the Ansible Playbook as you can see from my Previous post. I see this in the Log of the Container:

**matrixserver matrix-synapse[34822]: 2022-05-17 14:04:52,684 - synapse.appservice.scheduler - 404 - ERROR - as-sender-matrix-hookshot-1 - Error creating appservice transaction**

There are some other (older) Issues from 2019 where Synapse had the same Issue (e.g. here: https://github.com/mautrix/whatsapp/issues/44)

I will try to set up the latest Synapse + Hookshot etc without Ansible and Docker and see if it works. But thats a job for the Weekend :D

**Comment by psolyca** [comment]
Ok if it's your weekend job ^^
I have narrowed down where the link is created but maybe it's the Matrix client !
Which client are you using ? I use Element.io (web and app)

**Comment by JustCodeIt4Head** [comment]
> Ok if it's your weekend job ^^ I have narrowed down where the link is created but maybe it's the Matrix client ! Which client are you using ? I use Element.io (web and app)

Same here. Could you try and use another Client?

**Comment by psolyca** [comment]
Same with another client.
But it's just the render of the link in the client cause the body content is well formed.
This is where all is done : https://github.com/matrix-org/matrix-hookshot/blob/ea6382faa13c97b75b1b940dc1d709fcfa9023a0/src/Connections/SetupConnection.ts#L145

**Comment by psolyca** [comment]
Yes, but I did not find where/when the UUID is stored !
It's create just before, used and a string is send but the UUID/URL is never saved somewhere.
I have never code TS so I'm trying to understand ^^

**Comment by psolyca** [comment]
I have proposed a fix. Will see.
Also for the rendering I have 2 versions, link or code.
