### ISSUE TITLE
UserAgent is hardcoded to 1.1.0

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-hookshot#359]
Which causes no end of confusion when debugging. Please fix this argh

https://github.com/matrix-org/matrix-hookshot/blob/ffd64cf2f530467f109b33c37d45dbce5432bf5e/src/UserAgent.ts#L1

**Comment by HarHarLinks** [comment]
populate UA by git tag (and missing that, hash?)

**Comment by tadzik** [comment]
Getting it out of package.json should be free since we're using matrix-appservice-bridge which comes with it [built-in](https://github.com/matrix-org/matrix-appservice-bridge/blob/develop/src/utils/package-info.ts#L19)
