### ISSUE TITLE
Webhook provided by bot is incorrect, webhook appearing in log is correct.

### ISSUE THREAD

**Issue by Qrrbrbirlbel** [matrix-org/matrix-hookshot#378]
The webhook provided by the bot in a DM is different than the one provided in the log.
The one from the bot is also not formatted correctly, though that could be a client-side misinterpretation, the raw body is

    You have bridged a webhook. Please configure your webhook source to use <code>http://<internalDomain>:9000/webhook/4015d498-5a8a-40d0-9912-06156c2a99d9</code>.

which gets renderes as

> You have bridged a webhook. Please configure your webhook source to use &lt;code>[http://&lt;internalDomain>:9000/webhook/4015d498-5a8a-40d0-9912-06156c2a99d9&lt;/code>](http://<internalDomain>:9000/webhook/4015d498-5a8a-40d0-9912-06156c2a99d9%3C/code%3E).

The `<code>` is put verbatim in the text and `</code>` is even part of the link.

I'm obvious able to clean the link, however the log provides:

    INFO 17:40:47:935 [Bridge] New connected added to !foIKJqAlxgtpOHDmLw:<externalDomain>: GenericHookConnection fff74e86-1619-4489-a65d-bf064d7e2f96
    ERROR 17:47:25:691 [MatrixHttpClient (REQ-60)] {
      errcode: 'M_FORBIDDEN',
      error: 'Application service has not registered this user (@_webhooks_foobar:<externalDomain>)'
    }
    ERROR 17:47:25:755 [Appservice] Error registering user: User ID is in use
    ERROR 17:47:25:783 [MatrixHttpClient (REQ-65)] {
      errcode: 'M_FORBIDDEN',
      error: 'You do not belong to any of the required rooms/spaces to join this room.'
    }

(note that the ERRORs are much later, probably when I send the first successfull POST, the user @_webhooks_foobar *does*  join and send a message in the end, though)  
and while

    curl -XPOST -d '{}' http://<internalDomain>:9000/webhook/4015d498-5a8a-40d0-9912-06156c2a99d9

gives me

    {"ok":false,"error":"Webhook not found"}

the one from the log

    curl -XPOST -d '{}' http://<internalDomain>:9000/webhook/fff74e86-1619-4489-a65d-bf064d7e2f96

does alright (and even works in production):

    {"ok":true}

**To Reproduce**
1. Create a room and invite the bot.
2. Send `!hookshot webhook Foobar`
3. Bot sends message to DM and line in log gets added as described above
4. The last `curl` shows up in the chatroom as `{"{}": ""}` under the username *Foobar (Webhook)*.

**Expected behavior**
The webhook provided in the DM should be
1. the correct one and
2. formatted correctly.

**Server:**
 - Synapse: 1.61.0
 - Hookshot: halfshot/matrix-hookshot:latest

**Client:**
 - OS: Ubuntu 22.04
 - Element: 1.10.14

**Additional context**
I can't use already added hooks after I missed the correct webhook in the log.

**Comment by HarHarLinks** [comment]
https://github.com/matrix-org/matrix-hookshot/blob/026d7f64b5e03b67b72d38dce96db3b6e8007391/src/Connections/SetupConnection.ts#L145

**Comment by psolyca** [comment]
I just write a fix. I have 2 possibilities for rendering, get ride of `md.renderInline` to let the client create the link or create a method to send the correct link in `<code></code>` tags.
Also I have fix the bad UUID #379.

**Comment by psolyca** [comment]
Also Duplicate #357 .

**Comment by Qrrbrbirlbel** [comment]
Update: When I get the widget working it does display the correct webhook.

> Also Duplicate #357 .

@psolyca I saw this but all the comments were talking about different issues.

**Comment by psolyca** [comment]
Yes it's 2 different problems but on the same line of code ^^
Like you, when I activate the widget I have the right webhook, see my comment https://github.com/matrix-org/matrix-hookshot/issues/357#issuecomment-1160802695
So #379 fix the bad UUID different on the AdminRoom and the widget.
I'm waiting for the second fix which fix the link in the AdminRoom.
Finally, it's the same problem but not the same way to get it ^^.

**Comment by Half-Shot** [comment]
#379 is fixed, closing.
