### ISSUE TITLE
Webhook returns 'Bad JSON value: float' when JSON payload contains a floating point number.

### ISSUE THREAD

**Issue by Qrrbrbirlbel** [matrix-org/matrix-hookshot#386]
**Describe the bug**
When a webhook receives a JSON payload with a floating point number, say
```
curl -XPOST -d '{"test": 2.3}' -H "Content-Type: application/json" http://<hookshotAdress>:9000/webhook/<hookKey>
```
it returns
```JSON
{"ok":false,"error":"Failed to process webhook"}
```
and Hookshot's log complains about a 'Bad JSON value: float':
```
ERROR 21:53:51:254 [MatrixHttpClient (REQ-63)] { errcode: 'M_BAD_JSON', error: 'Bad JSON value: float' }
WARN 21:53:51:255 [Bridge] Failed to handle generic webhook Error: Failed to send Matrix message
    at MessageSenderClient.sendMatrixMessage (/bin/matrix-hookshot/MatrixSender.js:89:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async GenericHookConnection.onGenericHook (/bin/matrix-hookshot/Connections/GenericHook.js:269:9)
    at async /bin/matrix-hookshot/Bridge.js:364:38
    at async Promise.all (index 0)
    at async LocalMQ.<anonymous> (/bin/matrix-hookshot/Bridge.js:355:13)
```
This happens either with a custom transformation function or without one set.

**Expected behavior**
The floating point number should parse correctly since [the JSON specification](https://json-schema.org/understanding-json-schema/reference/numeric.html#number) allows it and the transformation function should be able to use it and its result should be sent to the room.

**Version**
 - Hookshot: 1.7.3 (latest)
 - Docker

**Additional context**
Unsurprisingly, the following payloads work as excepted:
```
curl -XPOST -d '{"test": 2}' -H "Content-Type: application/json" http://<hookshotAdress>:9000/webhook/<hookKey>
curl -XPOST -d '{"test": "2.3"}' -H "Content-Type: application/json" http://<hookshotAdress>:9000/webhook/<hookKey>
```

However, since I don't have any way to change the formatting of the payload, this can't be considered a workaround (and would misrepresent data).

Matrix defines its own “canonical JSON” as per [Appendix 1.3](https://spec.matrix.org/v1.3/appendices/#canonical-json) of its specification. However, in my opinion, the webhook's JSON payload has no relation to Matrix' JSON specification and needn't to adhere to Matrix' format.

Related?
* https://github.com/matrix-org/synapse/blob/9dde9c9f01ff8ed4c60314f10d97261739ea0547/synapse/events/utils.py#L469
* https://github.com/turt2live/matrix-dimension/issues/396#issue-792562399 uses the workaround of truncating the float.

## Speculation

It looks like the actual processing of the payload and possibly applying the transformation function aren't the problem but the actual sending of the message to Matrix is. Since Hookshot adds the full JSON payload to the message it sends to Matrix in

https://github.com/matrix-org/matrix-hookshot/blob/c36a5e7d60f190c5bc074c0b048152ca443d658d/src/Connections/GenericHook.ts#L342

this has to be root cause since here `2.3` wouldn't be allowed but `data` *suddenly* becomes part of the Matrix JSON.

**Comment by Half-Shot** [comment]
Yep, I think your speculation is spot on. Matrix (quietly) doesn't seem to support floats in it's JSON which means we're going to be affected by it, since we blindly paste the user input into the event.

I think realistically we might have to encode the floating values in objects as strings to be compliant with Matrix, at the risk of transforming input. It's a bit of a shame that Matrix doesn't specify the correct way to handle float values.
