### ISSUE TITLE
Widget connection failures should explain what went wrong

### ISSUE THREAD

**Issue by AndrewFerr** [matrix-org/matrix-hookshot#423]
**Is your feature request related to a problem? Please describe.**
When adding a connection via a widget fails, a message of "Failed to create connection" is added near the top of the widget page.  This isn't very helpful, though, as it doesn't explain what caused the failure, or what should be done about it.

As an aside, this error message doesn't go away if a connection is successfully added later.  It only goes away on the next visit to the connection management page.

**Describe the solution you'd like**
The error message should explain what can be done to resolve the failed connection, like making sure the repo exists, or making sure it has been configured to accept communications from Hookshot.

This information is already available in the HTTP response of the connection attempt, via the error object thrown by the failed connection attempt.

**Describe alternatives you've considered**
Each widget could use their own custom error messages for each error they catch, instead of showing the message of the thrown error.  But, this could result in duplicated work.

**Additional context**
Example for the in-progress GitHub widget:
![image](https://user-images.githubusercontent.com/3271094/180515764-ae9cc5ec-7ac5-4dd7-9ab3-c54bbf19acd1.png)

**Comment by Half-Shot** [comment]
Fixed by https://github.com/matrix-org/matrix-hookshot/pull/459
