### ISSUE TITLE
Provisioning fails if bot isn't already in room

### ISSUE THREAD

**Issue by AndrewFerr** [matrix-org/matrix-hookshot#456]
**Describe the bug**
When using a Hookshot-equipped Dimension to check available bridges for a room that the Hookshot bot isn't already a member of, Dimension shows Hookshot bridges (Github, Webhooks, etc) as unavailable.

This happens because this flow triggers a bad property lookup in Hookshot code.

**To Reproduce**
1. Configure Dimension & Hookshot
2. Create a new room
3. In Element Web, click ⓘ -> "Add widgets, bridges & bots"
4. See Hookshot bridges displayed with a ⚠
5. Click on any of the bridges to see an error popup of "This integration is offline or unavailable"

This can be fixed by inviting the Hookshot bot to the room.

**Expected behavior**
Dimension's bridge list appear to hit errors if Hookshot's bot isn't in a room.

If Hookshot bridges require the bot to be in the room, it should ideally be auto-invited.

**Screenshots**
![image](https://user-images.githubusercontent.com/3271094/186507711-3ba4a99b-9cc2-47e7-a49c-655ced0a5014.png)

**Comment by Half-Shot** [comment]
#456 fixed this.
