### ISSUE TITLE
Enhance gitlab comments display

### ISSUE THREAD

**Issue by gaelgatelement** [matrix-org/matrix-hookshot#531]
It could be great to add `\n` before `>` in gitlab comments message.
It would make a reading a little bit simpler

**Comment by jaller94** [comment]
* Minimum: The `formatted_body` should use `<p>` tags to separate the info and the quote.
* Ideal solution: In `format_body` wrap the quote in a `<blockquote>` tag. Remove the leading `>`.

## Example event content
```json
{
    "body": "**Christian Paul** commented on MR [new-vector/modular/modular-ansible#1789](https://gitlab.com/jaller94/foo/-/merge_requests/1): \"Test issue\" with one comment\n\n> How many Mudkips does it take to change a light bulb?",
    "format": "org.matrix.custom.html",
    "formatted_body": "<strong>Christian Paul</strong> commented on MR <a href=\"https://gitlab.com/jaller94/foo\">jaller94/foo#1</a>: &quot;Test issue&quot; with one comment\n\n&gt; How many Mudkips does it take to change a light bulb?",
    "msgtype": "m.notice"
  },
```

**Comment by jaller94** [comment]
The reason this is all rendered in one line is the use of `md.renderInline`.

https://github.com/matrix-org/matrix-hookshot/blob/0eabb9e3a7d734c4f5a73c3662825a41a2ca0d0e/src/Connections/GitlabRepo.ts#L658
