### ISSUE TITLE
Improve Gitlab permission checking

### ISSUE THREAD

**Issue by benbz** [matrix-org/matrix-hookshot#538]
Given:
* I am a member of a group `o` on a Gitlab instnace
* Group `o` is given owner permissions on another group `i`
* Group `i` has a sub-project `s`
* `/api/v4/projects/<project id>` with my Gitlab PAT returns:
```
  "permissions": {
    "project_access": null,
    "group_access": null
  }
```

This means that Hookshot decides I don't have the access level to setup the webhooks on project `s`

Options:
* Assume Gitlab 15.4 and consider using https://docs.gitlab.com/ee/api/members.html#get-a-member-of-a-group-or-project-including-inherited-and-invited-members which should make this visible via https://gitlab.com/gitlab-org/gitlab/-/merge_requests/83214
* If `/api/v4/projects/<project id>` returns something (i.e. I can view the project) then attempt to add the hook regardless and interpret the response rather than deciding I don't have access pre-emptively

**Comment by Half-Shot** [comment]
Seems to suggest it was introduced in [Introduced](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/17744) 12.4. The test instance we use also supports it.

**Comment by benbz** [comment]
> > Assume Gitlab 15.4 and consider using https://docs.gitlab.com/ee/api/members.html#get-a-member-of-a-group-or-project-including-inherited-and-invited-members which should make this visible via https://gitlab.com/gitlab-org/gitlab/-/merge_requests/83214
> 
> Seems to suggest it was [introduced](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/17744) 12.4. The test instance we use also supports it.

That API currently isn't returning inherited members on my Gitlab instance. I believe this is because of https://gitlab.com/gitlab-org/gitlab/-/merge_requests/83214 and that the Gitlab is on 15.2

**Comment by Half-Shot** [comment]
Ah :L
