### ISSUE TITLE
Give ability to disable error reporting into matrix rooms

### ISSUE THREAD

**Issue by etkecc** [matrix-org/matrix-hookshot#541]
Please, give ability to disable errors like

```
Error fetching https://github.com/Half-Shot/matrix-appservice-discord/tags.atom: timeout of 10000ms exceeded
```

in the matrix rooms

**Comment by HarHarLinks** [comment]
Related #493

I've posted some related ideas to improve error behaviour instead of disabling it outright to chat, quoted here for convenience:

> alternatively to showing the rss error on first timeout(?) and increasing the timeout from 10s to 30s, it could only show it on consecutive poll timeouts?
so if it times out once then it fails silently, but if $interval minutes later it times out again, then it sends an error to matrix.
the argument being that feeds should not be so time sensitive since you probably don't expect them to be absolutely realtime

> Maybe the bridge could consolidate multiple RSS timeout errors into one message instead of repeating it for potentially every feed a room is subscribed to?

**Comment by HarHarLinks** [comment]
It would be neat to have more error resilience on one hand, but also error reporting only to admin rooms for example on the other.

**Comment by Half-Shot** [comment]
Yeah, suspect you are both right. We should reduce the amount of noise from hookshot in the rooms, but also try to fix the timeouts.

**Comment by vranki** [comment]
I'd like to have timeout error disabled by default. In current form it just spams room if there is a random glitch. If the feed URL can't be reached, it could be displayed in the widget.

**Comment by HarHarLinks** [comment]
> If the feed URL can't be reached, it could be displayed in the widget.

i get that y'all don't want to get spammed. personally I bumped the timeout from 10s to 30s and it's fine apart from very few exceptions.

if you disable errors in chat, how will you notice that a feed broke? do you check the widget every now and then manually? or do you just not care and accept that feeds may silently disappear/break?

**Comment by SISheogorath** [comment]
I would suggest to change the threshold for the errors. A single timeout doesn't mean anything. If a feed couldn't be fetched for a week, this is a legitimate concern. But being unsuccessful once? Nope, please don't, a matrix room is not a (de-)centralised log system. This only leads to alert fatigue.

**Comment by Half-Shot** [comment]
Hiya, sorry about the noise. I had thought this *did* only alert on several failures although I think that logic may not be as smooth as we hoped. I'll put in something to ensure it doesn't make so much noise. Please hang tight.

**Comment by HarHarLinks** [comment]
This appears to have been resolved with a very black and white decision users now have to make Is there another more nuanced option planned?
