### ISSUE TITLE
More info in the „You have bridged a webhook“ message

### ISSUE THREAD

**Issue by weeman1337** [matrix-org/matrix-hookshot#619]
Use cases are for example looking up URLs for webhooks or to know when and where I configured them.

I would suggest changing

```
You have bridged a webhook. Please configure your webhook source to use https://example.com/
```

to

```
You have bridged the webhook „hook name“ in #room:example.com.
Please configure your webhook source to use https://example.com/
```

**Comment by Half-Shot** [comment]
Sounds like a nice low hanging fruit for someone :)

**Comment by weeman1337** [comment]
:upside_down_face: „someone“ could probably be me in the next days…
