### ISSUE TITLE
Unread notification for `m.notice` in e2ee room

### ISSUE THREAD

**Issue by weeman1337** [matrix-org/matrix-hookshot#638]
Steps to reproduce

- Set up hookshot with e2ee support
- Create an e2ee room
- Create a webhook inside
- Trigger the webhook

Expected: `m.notice` without unread count
What happens instead: Unread count show (1)

Tested with Element Web 1.11.20

---

I think this is an „upstream issue“ with the Matrix spec somehow. Still filing here as a hookshot problem, because it makes it unusable in encrypted rooms, at least in the environment, where I want to introduce it. In unencrypted rooms you can decide whether hookshot should send a notice or a message, depending on the message importance. In encrypted rooms everything increments unread count.

**Comment by Half-Shot** [comment]
Sounds clientside for sure, but annoying nonetheless.

**Comment by Half-Shot** [comment]
So digging into this with help from the Synapse team, we figure that Element (Web) actually should be calculating it's own notifications for encrypted events. However, digging into it reveals:

- Unread messages for all room types is calculated by the server https://github.com/matrix-org/matrix-js-sdk/blob/f00f70bfb8e94c7f0b3606b49c689c75ecb12fdc/src/sync.ts#L1289-L1306, with highlights being deferred to the client only.
- On decryption we run https://github.com/matrix-org/matrix-js-sdk/blob/c309fe69426d701893ebee315105f8fa8fef03f8/src/client.ts#L9424
- Ultimately we process the rules in https://github.com/matrix-org/matrix-js-sdk/blob/bba4a35665b99c988064f8485dce5f0fb525cdc8/src/pushprocessor.ts#L283, which doesn't take the `SuppressNotices` rule into account.

**Comment by Half-Shot** [comment]
Bug filed and investigation to continue on https://github.com/vector-im/element-web/issues/24448.

**Comment by weeman1337** [comment]
A similar problem exists for Element Android.
Fixing it for Element Web only doesn't really solve this :frowning_face: .

**Comment by Half-Shot** [comment]
I think it's ultimately down to the Element (product) team to solve this, rather than leaving it open on our bridge. I will solve it for Element Web as a proof of how it should work, to be taken by other teams.
