### ISSUE TITLE
We need to be more versatile in our RSS feed handling

### ISSUE THREAD

**Issue by tadzik** [matrix-org/matrix-hookshot#673]
https://github.com/matrix-org/matrix-hookshot/pull/670 resolved a couple issues, but also introduced a regression in other feeds.

At the same time, the [sanity check we do on content-type](https://github.com/matrix-org/matrix-hookshot/blob/main/src/Connections/FeedConnection.ts#L66) may be dropping feeds that shouldn't be dropped – production deployment saw plenty of `Feed responded with a content type of "text/html; charset=utf-8", which doesn't look like an RSS/Atom feed`, which could be a misuse of hookshot (submitting actually invalid feed URLs), or could be some feeds in the wild that are valid, but served with an invalid content-type.

We should compile a list of feeds that are known to cause problems, and ideally have tests in place to make sure that we can handle all of them correctly.

Known offenders:

 - `https://www.debian.org/News/news: Feed not recognized as RSS 1 or 2.` – regressed in #670?
 - Whatever #670 was fixing (@Half-Shot?)
 - to be continued

**Comment by vranki** [comment]
Not sure if this is handled yet, but could you make sure feeds without optional title tag look sane. Check this issue on NEB github for details: https://github.com/matrix-org/go-neb/issues/383

**Comment by vranki** [comment]
Ok, that should generate a link with URL preview for popular Matrix clients.

There's no plain text fallback though - will it have the actual URL when viewed by plain text clients and IRC bridge?

**Comment by vranki** [comment]
Here is an example of non-working RSS feed: https://www.taivaanvahti.fi/observations/rss

The content-type is indeed wrong, but otherwise it's valid RSS. The old NEB bot was able to subscribe to it.

**Comment by vranki** [comment]
Mastodon rss feeds still generate linkless messages in rooms. Has this really been fixed and/or deployed in use in Element Feeds bot instance?

**Comment by vranki** [comment]
@tadzik could you reopen this or open another issue for remaining bugs? For example Mastodon RSS links are still broken although it is valid RSS.

**Comment by vranki** [comment]
Confirmed working now. Thanks!
