### ISSUE TITLE
The feed bot keeps repeating some items

### ISSUE THREAD

**Issue by subbink** [matrix-org/matrix-hookshot#687]
I had subscribed to [bits of freedom's feed](https://www.bitsoffreedom.nl/feed/) using the migration option of the new feed bot.
This feed keeps repeating some items with every fetch.

I would expect that it would only show new items if they appear.

At first glance it seems that items without a category tag are repeated every time.

[bof-feed.xml.gz](https://github.com/matrix-org/matrix-hookshot/files/11068074/bof-feed.xml.gz) is a copy of the xml that caused an issue.

At the moment I have unsubscribed from the feed to keep other feeds visible.

Please let me know if I can help with testing.

**Comment by Half-Shot** [comment]
Looks like this got done!

**Comment by subbink** [comment]
I can confirm that the feed no longer repeats items.
