### ISSUE TITLE
Poor error message after allowing github integration

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-hookshot#710]
I allowed github access on [matrix-org/matrix-rust-sdk](https://github.com/matrix-org/matrix-rust-sdk) for the element.io GitHub Integration. Afterwards I saw this screen:

![image](https://user-images.githubusercontent.com/1389908/231233415-ac33dc84-4ae1-4b40-864d-8841216c33d4.png)

The error message comes from [here](https://github.com/matrix-org/matrix-hookshot/blob/c6f975b39045b3b6ef6b6c56e7781be56850500b/web/oauth.tsx#L48)

**Comment by Half-Shot** [comment]
Yeah, tediously there is scarce documentation on what states this can be in, so we've only documented the ones we've encountered. This one means it's in a pending state, so we need a PR to go make the text nicer.
