### ISSUE TITLE
$LINK is [markdown title](markdown link) rather than just the link

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix-hookshot#731]
I set a template `$FEEDTITLE: $AUTHOR $TITLE <$LINK> - $SUMMARY` expecting to get the name of the feed (as defined by itself), author if it exists, title, link and a summary of the post.

What I received instead was `Yle News | Tuoreimmat uutiset:  OP: Apartment prices, demand continue descent <[OP: Apartment prices, demand continue descent](https://yle.fi/a/74-20029412?origin=rss)> - For the first time, the financial group calculated which cities had the most — and least — affordable housing situations.` where the title repeating twice was unexpected as was the link having formatting.

**Comment by Half-Shot** [comment]
#737 will introduce a $URL template option which is the bare url.
