### ISSUE TITLE
RSS bot is down

### ISSUE THREAD

**Issue by bkil** [matrix-org/matrix-hookshot#778]
It hasn't fetched or forwarded new feed entries for 1.5 days now and fails to reconfigure itself. Last successful fetch was: `6/9/2023, 6:42:11 AM`. Confirmed by another user in another room.

Do you have a public service health dashboard that we could monitor for such issues (or subscribe to via RSS...)?

**Comment by bkil** [comment]
@Danie10  It's forwarding a few messages for a few minutes than goes blank for days. i'd wait a few more days to see whether it got back online. I can only hope that a post mortem will be published once it's fixed.

**Comment by Danie10** [comment]
@bkil yep you're right - this morning's posts has not gone through again.

**Comment by Half-Shot** [comment]
We've had a few attempts at speeding it up last week, please shout if this hasn't improved. Also, let's continue this on https://github.com/vector-im/element-integration-manager/issues/99 which is the repo for the element.io maintained version.
