### ISSUE TITLE
FeedReader can somehow create itself invalid accountData

### ISSUE THREAD

**Issue by tadzik** [matrix-org/matrix-hookshot#785]
I see this popping up in the logs after a restart

`ERROR 07:57:36:953 [FeedReader] Failed to load seen feed entries from accountData: Error: Invalid account data:  must NOT have additional properties. This may result in skipped entries`

This causes an accountData reset, and like it says: potentially skipped entries, since we treat each feed fetch after each startup as the "initial sync" where no entries are reported.

Further investigation is needed as to how do these invalid entries pop up in there, and in what form. I'll leave the instance in question to cook for a while and take a peek inside accountData to check it out.

**Comment by Half-Shot** [comment]
We've dropped account data in it's entirety in #786
