### ISSUE TITLE
E2EE instability warning in docs - still applicable?

### ISSUE THREAD

**Issue by ownerer** [matrix-org/matrix-hookshot#845]
This is a follow-up to #594 seeing as that one's closed and new replies are seemingly going unnoticed.
There is currently still a warning in the docs:
<img width="579" alt="image" src="https://github.com/matrix-org/matrix-hookshot/assets/24565568/c1d3eb6e-655f-4cdc-8e56-7eba60ab293d">
But the issue it refers to has been closed.
So the question is: is E2EE still unstable?
If so, how?
If not, can the warning in the docs be removed?
What about the experimental features on Synapse's side?
Thanks for clarifying.

**Comment by Half-Shot** [comment]
We might be able to tone it down a bit, but unfortunately the feature still depends on unstable bits of Matrix spec so we can't call it stable either. I'll see if we can revise it a bit.

**Comment by Half-Shot** [comment]
The warning has now been removed as of #989
