### ISSUE TITLE
[RSS bot] Include items lacking certain fields (e.g. <title>)

### ISSUE THREAD

**Issue by bkil** [matrix-org/matrix-hookshot#888]
Due to this issue, Mastodon feed subscription doesn't work.

Some feeds may be produced by buggy software, and thus lack some of the fields many developers assume to be mandatory. When possible, items could still be synthesized via generic text.

All what is really required from a user perspective in an item is a link that the user can click on

* When `link` is missing, try to parse the `guid` or `id` as a link. Lacking that, post a link to the origin instead so the user could still get notified when something is new and check it out manually.
* When the published or updated date is missing, assume it is the timestamp of the fetch
* When `title` is missing, show the date, feed name or some generic link text instead

**Comment by bkil** [comment]
Related: https://github.com/withastro/astro/issues/9577

**Comment by vranki** [comment]
Note that title element is optional in RSS. Mastodon is producing valid feeds.

**Comment by Half-Shot** [comment]
Sorry, to clarify are you saying Hookshot is skipping entries without a title entirely?

**Comment by bkil** [comment]
This is our present understanding (i.e., the major observable difference between a feed that can be followed by Hookshot and one that can not), but we have not bisected it at an XML level - should probably better be done in a unit test

**Comment by Half-Shot** [comment]
From my testing (https://github.com/matrix-org/matrix-hookshot/tree/hs/check-mastodon-style-rss-feeds), this doesn't seem to be the case. When we encounter a mastodon-style feed, the result is:

`New post in @UserName: [http://feed-item](http://feed-item/123456)`

**Comment by bkil** [comment]
Could you please share a link to a Mastodon feed that is fetched correctly so I can test it myself? Maybe you have blocked some of the feeds we are subscribed to.

**Comment by vranki** [comment]
I have seen quite random behavior with Feeds bot recently. I thought the "bug" was fixed but then some feeds don't seem to work randomly. This is starting to sound like issue with the Feeds bot operated by Element. Not sure where that should be reported to.

**Comment by bkil** [comment]
If you can give me a working Mastodon feed link, then this issue can be closed, as the root cause then may be #844

**Comment by vranki** [comment]
> If you can give me a working Mastodon feed link, then this issue can be closed, as the root cause then may be #844

https://sauna.social/tags/leffat.rss (a hashtag feed) provided a toot yesterday.

**Comment by Half-Shot** [comment]
> I have seen quite random behavior with Feeds bot recently. I thought the "bug" was fixed but then some feeds don't seem to work randomly. This is starting to sound like issue with the Feeds bot operated by Element. Not sure where that should be reported to.

Also me, via https://github.com/element-hq/element-integration-manager/issues/108. It sounds like this is a skipping entries bug for sure.
